package com.zimbra.oauth.utilities;

public enum OAuth2Error {

	GENERIC_OAUTH_ERROR,
	CONFIGURATION_ERROR,
	INVALID_OPERATION_ERROR,
	USER_UNAUTHORIZED_ERROR,
	INVALID_RESPONSE_ERROR,
	USER_FORBIDDEN_ERROR,
	UNREACHABLE_HOST_ERROR,
	SERVICE_NOT_AVAILABLE_ERROR,
	INVALID_CLIENT_ERROR
}
